In [4]:
#slicing
import numpy as np
a = np.array([[1,2], [3,4]])

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
a.shape

(2, 2)

In [11]:
b = a[0:1, 1:2]  # 범위지정을 차원별로 할 수 있으며 :라는 기호를 쓴다.
b

array([[2]])

In [12]:
c = a[:, 1:2]  # 전체범위를 표현할때는 그냥 : 라고 적으면 된다.
c

array([[2],
       [4]])